ALTER TABLE user_read_history ENGINE=INNODB;

ALTER TABLE subject ADD COLUMN pin TINYINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE subject ADD INDEX IDX_SUBJECT_PIN(pin);

ALTER TABLE topic ADD COLUMN pin TINYINT UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE topic ADD INDEX IDX_TOPIC_PIN(pin);