[workspace.package]
version = "2.2.5"
authors = ["axumrs <team@mail.axum.eu.org>"]
edition = "2024"

[package]
name = "axum-rs"
version.workspace = true
authors.workspace = true
edition.workspace = true

[workspace]
members = ["."]
resolver = "3"

[dependencies]
dioxus.workspace = true

[workspace.dependencies]
dioxus = { version = "0.7.1", features = ["router", "fullstack"] }

[features]
default = ["web"]
web = ["dioxus/web"]
server = ["dioxus/server"]
