[application]

[web.app]

# HTML title tag content
title = "AXUM中文网 - 带你使用 axum 构建企业应用"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
